ASR_config: Utils/ASR/config.yml
ASR_path: Utils/ASR/epoch_00080.pth
F0_path: Utils/JDC/bst.t7
batch_size: 32
device: cpu
epochs_1st: 200
epochs_2nd: 100
first_stage_path: first_stage.pth
load_only_params: false
log_dir: Models/LJSpeech
log_interval: 10
loss_params:
  TMA_CEloss: false
  TMA_epoch: 20
  lambda_F0: 1.0
  lambda_adv: 1.0
  lambda_dur: 1.0
  lambda_fm: 0.1
  lambda_mel: 5.0
  lambda_mono: 1.0
  lambda_norm: 1.0
  lambda_reg: 1.0
  lambda_s2s: 1.0
model_params:
  dim_in: 64
  dropout: 0.2
  hidden_dim: 512
  max_conv_dim: 512
  n_layer: 3
  n_mels: 80
  n_token: 178
  style_dim: 128
multigpu: false
optimizer_params:
  lr: 0.0001
preprocess_params:
  spect_params:
    hop_length: 300
    n_fft: 2048
    win_length: 1200
  sr: 24000
pretrained_model: ''
save_freq: 2
second_stage_load_pretrained: false
train_data: Data/train_list.txt
val_data: Data/val_list.txt
